// kv.proto is the client-facing API for the replicated KV store (Phase 3).
//
// Clients talk to any node; followers return NOT_LEADER with a hint so the
// client can retry against the current leader. Every mutating RPC carries
// client_id + request_id for exactly-once semantics enforced by the state machine.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	NotLeader     bool                   `protobuf:"varint,4,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *GetResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *GetResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviousValue []byte                 `protobuf:"bytes,1,opt,name=previous_value,json=previousValue,proto3" json:"previous_value,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	NotLeader     bool                   `protobuf:"varint,3,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetPreviousValue() []byte {
	if x != nil {
		return x.PreviousValue
	}
	return nil
}

func (x *PutResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *PutResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *PutResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type CASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Expect        []byte                 `protobuf:"bytes,4,opt,name=expect,proto3" json:"expect,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASRequest) Reset() {
	*x = CASRequest{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASRequest) ProtoMessage() {}

func (x *CASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASRequest.ProtoReflect.Descriptor instead.
func (*CASRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *CASRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CASRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CASRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CASRequest) GetExpect() []byte {
	if x != nil {
		return x.Expect
	}
	return nil
}

func (x *CASRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swapped       bool                   `protobuf:"varint,1,opt,name=swapped,proto3" json:"swapped,omitempty"`
	PreviousValue []byte                 `protobuf:"bytes,2,opt,name=previous_value,json=previousValue,proto3" json:"previous_value,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	NotLeader     bool                   `protobuf:"varint,4,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResponse) Reset() {
	*x = CASResponse{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResponse) ProtoMessage() {}

func (x *CASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResponse.ProtoReflect.Descriptor instead.
func (*CASResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *CASResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

func (x *CASResponse) GetPreviousValue() []byte {
	if x != nil {
		return x.PreviousValue
	}
	return nil
}

func (x *CASResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *CASResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *CASResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type ExecuteOnceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClientId  string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Key       string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// If true, use CAS with expect=previous_value (zero-length expect means absent key).
	UseCas        bool   `protobuf:"varint,5,opt,name=use_cas,json=useCas,proto3" json:"use_cas,omitempty"`
	Expect        []byte `protobuf:"bytes,6,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOnceRequest) Reset() {
	*x = ExecuteOnceRequest{}
	mi := &file_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOnceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOnceRequest) ProtoMessage() {}

func (x *ExecuteOnceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOnceRequest.ProtoReflect.Descriptor instead.
func (*ExecuteOnceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteOnceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExecuteOnceRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ExecuteOnceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExecuteOnceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecuteOnceRequest) GetUseCas() bool {
	if x != nil {
		return x.UseCas
	}
	return false
}

func (x *ExecuteOnceRequest) GetExpect() []byte {
	if x != nil {
		return x.Expect
	}
	return nil
}

type ExecuteOnceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	NotLeader     bool                   `protobuf:"varint,4,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOnceResponse) Reset() {
	*x = ExecuteOnceResponse{}
	mi := &file_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOnceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOnceResponse) ProtoMessage() {}

func (x *ExecuteOnceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOnceResponse.ProtoReflect.Descriptor instead.
func (*ExecuteOnceResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteOnceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecuteOnceResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecuteOnceResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *ExecuteOnceResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *ExecuteOnceResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	State         []byte                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{8}
}

func (x *CheckpointRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckpointRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CheckpointRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	NotLeader     bool                   `protobuf:"varint,3,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *CheckpointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckpointResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *CheckpointResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *CheckpointResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *WatchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WatchResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x04kvpb\"Z\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\x93\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x04 \x01(\bR\tnotLeader\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\x04R\bleaderId\"p\n" +
	"\n" +
	"PutRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"\x8e\x01\n" +
	"\vPutResponse\x12%\n" +
	"\x0eprevious_value\x18\x01 \x01(\fR\rpreviousValue\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x03 \x01(\bR\tnotLeader\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderId\"\x88\x01\n" +
	"\n" +
	"CASRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06expect\x18\x04 \x01(\fR\x06expect\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"\xa8\x01\n" +
	"\vCASResponse\x12\x18\n" +
	"\aswapped\x18\x01 \x01(\bR\aswapped\x12%\n" +
	"\x0eprevious_value\x18\x02 \x01(\fR\rpreviousValue\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x04 \x01(\bR\tnotLeader\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\x04R\bleaderId\"\xa9\x01\n" +
	"\x12ExecuteOnceRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x17\n" +
	"\ause_cas\x18\x05 \x01(\bR\x06useCas\x12\x16\n" +
	"\x06expect\x18\x06 \x01(\fR\x06expect\"\x95\x01\n" +
	"\x13ExecuteOnceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x04 \x01(\bR\tnotLeader\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\x04R\bleaderId\"e\n" +
	"\x11CheckpointRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state\"~\n" +
	"\x12CheckpointResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x03 \x01(\bR\tnotLeader\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderId\" \n" +
	"\fWatchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\rWatchResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found2\xc1\x02\n" +
	"\x02KV\x12*\n" +
	"\x03Get\x12\x10.kvpb.GetRequest\x1a\x11.kvpb.GetResponse\x12*\n" +
	"\x03Put\x12\x10.kvpb.PutRequest\x1a\x11.kvpb.PutResponse\x12*\n" +
	"\x03CAS\x12\x10.kvpb.CASRequest\x1a\x11.kvpb.CASResponse\x12B\n" +
	"\vExecuteOnce\x12\x18.kvpb.ExecuteOnceRequest\x1a\x19.kvpb.ExecuteOnceResponse\x12?\n" +
	"\n" +
	"Checkpoint\x12\x17.kvpb.CheckpointRequest\x1a\x18.kvpb.CheckpointResponse\x122\n" +
	"\x05Watch\x12\x12.kvpb.WatchRequest\x1a\x13.kvpb.WatchResponse0\x01B6Z4github.com/AnushSonone/kill-my-cluster/internal/kvpbb\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_kv_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: kvpb.GetRequest
	(*GetResponse)(nil),         // 1: kvpb.GetResponse
	(*PutRequest)(nil),          // 2: kvpb.PutRequest
	(*PutResponse)(nil),         // 3: kvpb.PutResponse
	(*CASRequest)(nil),          // 4: kvpb.CASRequest
	(*CASResponse)(nil),         // 5: kvpb.CASResponse
	(*ExecuteOnceRequest)(nil),  // 6: kvpb.ExecuteOnceRequest
	(*ExecuteOnceResponse)(nil), // 7: kvpb.ExecuteOnceResponse
	(*CheckpointRequest)(nil),   // 8: kvpb.CheckpointRequest
	(*CheckpointResponse)(nil),  // 9: kvpb.CheckpointResponse
	(*WatchRequest)(nil),        // 10: kvpb.WatchRequest
	(*WatchResponse)(nil),       // 11: kvpb.WatchResponse
}
var file_proto_kv_proto_depIdxs = []int32{
	0,  // 0: kvpb.KV.Get:input_type -> kvpb.GetRequest
	2,  // 1: kvpb.KV.Put:input_type -> kvpb.PutRequest
	4,  // 2: kvpb.KV.CAS:input_type -> kvpb.CASRequest
	6,  // 3: kvpb.KV.ExecuteOnce:input_type -> kvpb.ExecuteOnceRequest
	8,  // 4: kvpb.KV.Checkpoint:input_type -> kvpb.CheckpointRequest
	10, // 5: kvpb.KV.Watch:input_type -> kvpb.WatchRequest
	1,  // 6: kvpb.KV.Get:output_type -> kvpb.GetResponse
	3,  // 7: kvpb.KV.Put:output_type -> kvpb.PutResponse
	5,  // 8: kvpb.KV.CAS:output_type -> kvpb.CASResponse
	7,  // 9: kvpb.KV.ExecuteOnce:output_type -> kvpb.ExecuteOnceResponse
	9,  // 10: kvpb.KV.Checkpoint:output_type -> kvpb.CheckpointResponse
	11, // 11: kvpb.KV.Watch:output_type -> kvpb.WatchResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
